name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:   
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ./cmd/gomobile
      run: go build -o alternative_gomobile_linux
      
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux_artifacts
        path: ./cmd/gomobile/alternative_gomobile_linux                    

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ./cmd/gomobile
      run: go build -o alternative_gomobile_macos
      
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos_artifacts
        path: ./cmd/gomobile/alternative_gomobile_macos
        
  upload-release:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    steps:

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux_artifacts

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos_artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            alternative_gomobile_linux
            alternative_gomobile_macos
